/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rs.ac.bg.fon.ps.view.form;

import java.awt.Frame;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import rs.ac.bg.fon.ps.view.form.util.FormMode;

/**
 *
 * @author USER
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuKlijenti = new javax.swing.JMenu();
        jUnosNovogKlijenta = new javax.swing.JMenuItem();
        jIzmenaPostojecegKlijenta = new javax.swing.JMenuItem();
        jBrisanjeKlijenta = new javax.swing.JMenuItem();
        jPretragaKlijenata = new javax.swing.JMenuItem();
        jMenuTreneri = new javax.swing.JMenu();
        jUnosNovogTrenera = new javax.swing.JMenuItem();
        jIzmenaTrenera = new javax.swing.JMenuItem();
        jPretragaTrenera = new javax.swing.JMenuItem();
        jMenuTreninzi = new javax.swing.JMenu();
        jZakazivanjeTreninga = new javax.swing.JMenuItem();
        jIzmenaTreninga = new javax.swing.JMenuItem();
        jPretragaTreninga = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna ekranska forma");

        jMenuKlijenti.setText("Klijenti ");

        jUnosNovogKlijenta.setText("Unos novog klijenta");
        jUnosNovogKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnosNovogKlijentaActionPerformed(evt);
            }
        });
        jMenuKlijenti.add(jUnosNovogKlijenta);

        jIzmenaPostojecegKlijenta.setText("Izmena klijenta");
        jIzmenaPostojecegKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIzmenaPostojecegKlijentaActionPerformed(evt);
            }
        });
        jMenuKlijenti.add(jIzmenaPostojecegKlijenta);

        jBrisanjeKlijenta.setText("Brisanje klijenta");
        jMenuKlijenti.add(jBrisanjeKlijenta);

        jPretragaKlijenata.setText("Pretraga klijenata");
        jMenuKlijenti.add(jPretragaKlijenata);

        jMenuBar1.add(jMenuKlijenti);

        jMenuTreneri.setText("Treneri");

        jUnosNovogTrenera.setText("Unos novog trenera");
        jMenuTreneri.add(jUnosNovogTrenera);

        jIzmenaTrenera.setText("Izmena trenera");
        jMenuTreneri.add(jIzmenaTrenera);

        jPretragaTrenera.setText("Pretraga trenera");
        jMenuTreneri.add(jPretragaTrenera);

        jMenuBar1.add(jMenuTreneri);

        jMenuTreninzi.setText("Treninzi");

        jZakazivanjeTreninga.setText("Zakazivanje treninga");
        jZakazivanjeTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZakazivanjeTreningaActionPerformed(evt);
            }
        });
        jMenuTreninzi.add(jZakazivanjeTreninga);

        jIzmenaTreninga.setText("Izmena treninga");
        jMenuTreninzi.add(jIzmenaTreninga);

        jPretragaTreninga.setText("Pretraga treninga");
        jPretragaTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPretragaTreningaActionPerformed(evt);
            }
        });
        jMenuTreninzi.add(jPretragaTreninga);

        jMenuBar1.add(jMenuTreninzi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIzmenaPostojecegKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIzmenaPostojecegKlijentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIzmenaPostojecegKlijentaActionPerformed

    private void jUnosNovogKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnosNovogKlijentaActionPerformed
      
    }//GEN-LAST:event_jUnosNovogKlijentaActionPerformed

    private void jZakazivanjeTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZakazivanjeTreningaActionPerformed
       
           /*try {
               new FrmUnosTreninga(this, true, FormMode.FORM_ADD).setVisible(true);
           } catch (Exception ex) {
               Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
           }*/

    }//GEN-LAST:event_jZakazivanjeTreningaActionPerformed

    private void jPretragaTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPretragaTreningaActionPerformed
        
            /*try {
                new FrmPrikazTreninga(this, true).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }*/
    }//GEN-LAST:event_jPretragaTreningaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jBrisanjeKlijenta;
    private javax.swing.JMenuItem jIzmenaPostojecegKlijenta;
    private javax.swing.JMenuItem jIzmenaTrenera;
    private javax.swing.JMenuItem jIzmenaTreninga;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuKlijenti;
    private javax.swing.JMenu jMenuTreneri;
    private javax.swing.JMenu jMenuTreninzi;
    private javax.swing.JMenuItem jPretragaKlijenata;
    private javax.swing.JMenuItem jPretragaTrenera;
    private javax.swing.JMenuItem jPretragaTreninga;
    private javax.swing.JMenuItem jUnosNovogKlijenta;
    private javax.swing.JMenuItem jUnosNovogTrenera;
    private javax.swing.JMenuItem jZakazivanjeTreninga;
    // End of variables declaration//GEN-END:variables

    public void jmiTreningNoviActionListener(ActionListener actionListener) {
        jZakazivanjeTreninga.addActionListener(actionListener);
    }

    public void jmiTreningPrikaziSveActionListener(ActionListener actionListener) {
        jPretragaTreninga.addActionListener(actionListener);
    }
}
