/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rs.ac.bg.fon.ps.view.form;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.Trener;
import rs.ac.bg.fon.ps.domain.Trening;
import rs.ac.bg.fon.ps.view.form.util.FormMode;

/**
 *
 * @author USER
 */
public class FrmUnosTreninga extends javax.swing.JDialog {

    /**
     * Creates new form FrmUnosTreningaNovo
     */
    public FrmUnosTreninga(java.awt.Frame parent, boolean modal, FormMode formMode) throws Exception {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareView(formMode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAzuriraj = new javax.swing.JButton();
        jBtnIzmene = new javax.swing.JButton();
        jBtnObrisi = new javax.swing.JButton();
        jBtnOdustani = new javax.swing.JButton();
        jBtnSacuvaj = new javax.swing.JButton();
        jLbDatum = new javax.swing.JLabel();
        jLbNapomena = new javax.swing.JLabel();
        jTxtDatum = new javax.swing.JTextField();
        jLbErDatum = new javax.swing.JLabel();
        jLbTreningID = new javax.swing.JLabel();
        jTxtTreningID = new javax.swing.JTextField();
        jLbErIdTreninga = new javax.swing.JLabel();
        jLbTrajanje = new javax.swing.JLabel();
        jTxtTrajanje = new javax.swing.JTextField();
        jLbErTrajanje = new javax.swing.JLabel();
        jLbTrener = new javax.swing.JLabel();
        jComboTrener = new javax.swing.JComboBox();
        jLbErTrener = new javax.swing.JLabel();
        jScrollPaneNapomena = new javax.swing.JScrollPane();
        jTextNapomena = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnAzuriraj.setText("Azuriraj");

        jBtnIzmene.setText("Izmene");
        jBtnIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzmeneActionPerformed(evt);
            }
        });

        jBtnObrisi.setText("Obrisi");

        jBtnOdustani.setText("Odustani");
        jBtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOdustaniActionPerformed(evt);
            }
        });

        jBtnSacuvaj.setText("Sacuvaj");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jLbDatum.setText("Datum: ");

        jLbNapomena.setText("Napomena:");

        jLbTreningID.setText("TreningID: ");

        jLbTrajanje.setText("Trajanje:");

        jTxtTrajanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTrajanjeActionPerformed(evt);
            }
        });

        jLbTrener.setText("Trener:");

        jTextNapomena.setColumns(20);
        jTextNapomena.setRows(5);
        jScrollPaneNapomena.setViewportView(jTextNapomena);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbTreningID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtTreningID))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLbTrajanje)
                                            .addComponent(jLbTrener))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtTrajanje)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLbErTrener, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboTrener, javax.swing.GroupLayout.Alignment.LEADING, 0, 397, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLbErTrajanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLbErIdTreninga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnObrisi)
                                    .addComponent(jBtnIzmene)
                                    .addComponent(jBtnOdustani)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbDatum)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLbErDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnAzuriraj)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbNapomena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addComponent(jBtnSacuvaj)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAzuriraj)
                    .addComponent(jLbDatum)
                    .addComponent(jTxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbErDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIzmene)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLbTreningID)
                        .addComponent(jTxtTreningID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnObrisi)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnOdustani))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbErIdTreninga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbTrener)
                                    .addComponent(jComboTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLbTrajanje)
                        .addGap(18, 18, 18)
                        .addComponent(jLbErTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbErTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbNapomena)
                    .addComponent(jScrollPaneNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSacuvaj))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtTrajanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTrajanjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTrajanjeActionPerformed

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed
        try {
            validateForm();
            Trening trening = new Trening();
        
            trening.setTreningId(Long.parseLong(jTxtTreningID.getText().trim()));
            trening.setNapomena(jTextNapomena.getText().trim());
            trening.setTrajanje(Double.parseDouble(jTxtTrajanje.getText().trim()));
            trening.setTrener((Trener) jComboTrener.getSelectedItem());
            trening.setDatumVreme(jTxtDatum.getText().trim());
        
            Controller.getInstance().addTrening(trening);
        
            JOptionPane.showMessageDialog(this, "Trening je uspesno zakazan!", "Dodat trening", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nisu pravilno uneta jedno ili sva polja", "Neuspesno zakazivanje treninga", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    private void jBtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnOdustaniActionPerformed

    private void jBtnIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzmeneActionPerformed
        
            try {
                new FrmUnosTreninga(null, true, FormMode.FORM_EDIT).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmUnosTreninga.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBtnIzmeneActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAzuriraj;
    private javax.swing.JButton jBtnIzmene;
    private javax.swing.JButton jBtnObrisi;
    private javax.swing.JButton jBtnOdustani;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JComboBox jComboTrener;
    private javax.swing.JLabel jLbDatum;
    private javax.swing.JLabel jLbErDatum;
    private javax.swing.JLabel jLbErIdTreninga;
    private javax.swing.JLabel jLbErTrajanje;
    private javax.swing.JLabel jLbErTrener;
    private javax.swing.JLabel jLbNapomena;
    private javax.swing.JLabel jLbTrajanje;
    private javax.swing.JLabel jLbTrener;
    private javax.swing.JLabel jLbTreningID;
    private javax.swing.JScrollPane jScrollPaneNapomena;
    private javax.swing.JTextArea jTextNapomena;
    private javax.swing.JTextField jTxtDatum;
    private javax.swing.JTextField jTxtTrajanje;
    private javax.swing.JTextField jTxtTreningID;
    // End of variables declaration//GEN-END:variables

    private void prepareView(FormMode formMode) throws Exception {
        fillComboTreneri();
        setupComponents(formMode);
    }

    private void fillComboTreneri() throws Exception {
        jComboTrener.removeAllItems();
       
       List <Trener> treneri = Controller.getInstance().getAllTreneri();
       for (Trener trener : treneri) {
           jComboTrener.addItem(trener);
       }
    }

    private void setupComponents(FormMode formMode) {
        switch(formMode) {
            case FORM_ADD:
                jBtnSacuvaj.setVisible(true);
                jBtnObrisi.setEnabled(false);
                jBtnOdustani.setVisible(true);
                jBtnIzmene.setEnabled(false);
                jBtnAzuriraj.setEnabled(false);
                break;
            case FORM_VIEW:
                jBtnSacuvaj.setEnabled(false);
                jBtnObrisi.setVisible(true);
                jBtnOdustani.setVisible(true);
                jBtnIzmene.setVisible(true);
                jBtnAzuriraj.setEnabled(false);
                
                jTxtTreningID.setEditable(false);
                jTxtDatum.setEditable(false);
                jTxtTrajanje.setEditable(false);
                jTextNapomena.setEditable(false);
                jComboTrener.setEditable(false);
                break;
            case FORM_EDIT:
                jBtnSacuvaj.setVisible(true);
                jBtnObrisi.setEnabled(false);
                jBtnOdustani.setVisible(true);
                jBtnIzmene.setEnabled(false);
                jBtnAzuriraj.setVisible(true);

                jTxtTreningID.setEnabled(false);
                jTxtDatum.setEnabled(false);
                jTextNapomena.setEnabled(false);
                break;
        }
    }

    private void validateForm() throws Exception {
        jLbErIdTreninga.setText("");
        jLbErDatum.setText("");
        jLbErTrajanje.setText("");
        jLbErTrener.setText("");
        
        String errorMes = "";
        
        String idTreninga = jTxtTreningID.getText().trim();
        String datum = jTxtDatum.getText().trim();
        String trajanje = jTxtTrajanje.getText().trim();
        Trener trener = (Trener) jComboTrener.getSelectedItem();
        
        if (idTreninga.isEmpty()) {
            jLbErIdTreninga.setText("Polje za ID treninga mora biti uneto!");
            errorMes += "Nije uneto polje za ID!";
        }
        
        if (datum.isEmpty()) {
            jLbErDatum.setText("Polje za datum i vreme mora biti uneto!");
            errorMes += "Nije uneto polje za datum i vreme";
        }
        
        if (trajanje.isEmpty()) {
            jLbErTrajanje.setText("Polje za trajanje treninga mora biti uneto!");
            errorMes += "Nije uneto polje za trajanje treninga";
        }
        
        if (trener == null) {
            jLbErTrener.setText("Trener mora biti izabran!");
            errorMes += "Nije izabran trener";
        }
        
        if (!errorMes.isEmpty()) {
            throw new Exception(errorMes);
        }
    }
}
