/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rs.ac.bg.fon.ps.view.form;

import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.Trener;
import rs.ac.bg.fon.ps.domain.Trening;
import rs.ac.bg.fon.ps.view.form.util.FormMode;

/**
 *
 * @author USER
 */
public class FrmUnosTreninga extends javax.swing.JDialog {

    /**
     * Creates new form FrmUnosTreninga
     */
    public FrmUnosTreninga(java.awt.Frame parent, boolean modal, FormMode formMode) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareView(formMode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbTreningID = new javax.swing.JLabel();
        jTxtTreningID = new javax.swing.JTextField();
        jLbDatum = new javax.swing.JLabel();
        jTxtDatum = new javax.swing.JTextField();
        jLbTrajanje = new javax.swing.JLabel();
        jTxtTrajanje = new javax.swing.JTextField();
        jLbNapomena = new javax.swing.JLabel();
        jScrollPaneNapomena = new javax.swing.JScrollPane();
        jTextNapomena = new javax.swing.JTextArea();
        jLbTrener = new javax.swing.JLabel();
        jComboTrener = new javax.swing.JComboBox<Object>();
        jBtnSacuvaj = new javax.swing.JButton();
        jLbErIdTreninga = new javax.swing.JLabel();
        jLbErDatum = new javax.swing.JLabel();
        jLbErTrajanje = new javax.swing.JLabel();
        jLbErTrener = new javax.swing.JLabel();
        jBtnObrisi = new javax.swing.JButton();
        jBtnIzmene = new javax.swing.JButton();
        jBtnOdustani = new javax.swing.JButton();
        jBtnAzuriraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zakazivanje treninga");

        jLbTreningID.setText("ID treninga:");

        jLbDatum.setText("Datum i vreme treninga: ");

        jLbTrajanje.setText("Duzina trajanja treninga:");

        jLbNapomena.setText("Napomena:");

        jTextNapomena.setColumns(3);
        jTextNapomena.setRows(5);
        jTextNapomena.setTabSize(20);
        jScrollPaneNapomena.setViewportView(jTextNapomena);

        jLbTrener.setText("Trener:");

        jBtnSacuvaj.setText("Sačuvaj");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jLbErIdTreninga.setForeground(new java.awt.Color(255, 0, 0));
        jLbErIdTreninga.setText(" ");

        jLbErDatum.setForeground(new java.awt.Color(255, 0, 0));

        jLbErTrajanje.setForeground(new java.awt.Color(255, 0, 0));

        jLbErTrener.setForeground(new java.awt.Color(255, 0, 0));

        jBtnObrisi.setText("Obriši");

        jBtnIzmene.setText("Omogući izmene");
        jBtnIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzmeneActionPerformed(evt);
            }
        });

        jBtnOdustani.setText("Odustani");
        jBtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOdustaniActionPerformed(evt);
            }
        });

        jBtnAzuriraj.setText("Azuriraj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLbErTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLbNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPaneNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLbTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLbErTrener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboTrener, 0, 234, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLbDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLbErIdTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLbErDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbTreningID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtTreningID, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnIzmene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jBtnObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAzuriraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbTreningID)
                            .addComponent(jTxtTreningID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbErIdTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbDatum)
                            .addComponent(jTxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLbErDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnAzuriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbTrajanje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbErTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLbNapomena))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbTrener))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLbErTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jBtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed
        try {
            validateForm();
            Trening trening = new Trening();
        
            trening.setTreningId(Long.parseLong(jTxtTreningID.getText().trim()));
            trening.setNapomena(jTextNapomena.getText().trim());
            trening.setTrajanje(Double.parseDouble(jTxtTrajanje.getText().trim()));
            trening.setTrener((Trener) jComboTrener.getSelectedItem());
            trening.setDatumVreme(jTxtDatum.getText().trim());
        
            Controller.getInstance().addTrening(trening);
        
            JOptionPane.showMessageDialog(this, "Trening je uspesno zakazan!", "Dodat trening", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nisu pravilno uneta jedno ili sva polja", "Neuspesno zakazivanje treninga", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    private void jBtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnOdustaniActionPerformed

    private void jBtnIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzmeneActionPerformed
        new FrmUnosTreninga(null, true, FormMode.FORM_UPDATE).setVisible(true);
    }//GEN-LAST:event_jBtnIzmeneActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAzuriraj;
    private javax.swing.JButton jBtnIzmene;
    private javax.swing.JButton jBtnObrisi;
    private javax.swing.JButton jBtnOdustani;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JComboBox<Object> jComboTrener;
    private javax.swing.JLabel jLbDatum;
    private javax.swing.JLabel jLbErDatum;
    private javax.swing.JLabel jLbErIdTreninga;
    private javax.swing.JLabel jLbErTrajanje;
    private javax.swing.JLabel jLbErTrener;
    private javax.swing.JLabel jLbNapomena;
    private javax.swing.JLabel jLbTrajanje;
    private javax.swing.JLabel jLbTrener;
    private javax.swing.JLabel jLbTreningID;
    private javax.swing.JScrollPane jScrollPaneNapomena;
    private javax.swing.JTextArea jTextNapomena;
    private javax.swing.JTextField jTxtDatum;
    private javax.swing.JTextField jTxtTrajanje;
    private javax.swing.JTextField jTxtTreningID;
    // End of variables declaration//GEN-END:variables

    private void prepareView(FormMode formMode) {
        fillComboTreneri();
        setupComponents(formMode);
    }

    private void fillComboTreneri() {
       jComboTrener.removeAllItems();
       
       List <Trener> treneri = Controller.getInstance().getAllTreneri();
       for (Trener trener : treneri) {
           jComboTrener.addItem(trener);
       }
    }

    private void validateForm() throws Exception{
        jLbErIdTreninga.setText("");
        jLbErDatum.setText("");
        jLbErTrajanje.setText("");
        jLbErTrener.setText("");
        
        String errorMes = "";
        
        String idTreninga = jTxtTreningID.getText().trim();
        String datum = jTxtDatum.getText().trim();
        String trajanje = jTxtTrajanje.getText().trim();
        Trener trener = (Trener) jComboTrener.getSelectedItem();
        
        if (idTreninga.isEmpty()) {
            jLbErIdTreninga.setText("Polje za ID treninga mora biti uneto!");
            errorMes += "Nije uneto polje za ID!";
        }
        
        if (datum.isEmpty()) {
            jLbErDatum.setText("Polje za datum i vreme mora biti uneto!");
            errorMes += "Nije uneto polje za datum i vreme";
        }
        
        if (trajanje.isEmpty()) {
            jLbErTrajanje.setText("Polje za trajanje treninga mora biti uneto!");
            errorMes += "Nije uneto polje za trajanje treninga";
        }
        
        if (trener == null) {
            jLbErTrener.setText("Trener mora biti izabran!");
            errorMes += "Nije izabran trener";
        }
        
        if (!errorMes.isEmpty()) {
            throw new Exception(errorMes);
        }
    }

    private void setupComponents(FormMode formMode) {
        switch(formMode) {
            case FORM_ADD:
                jBtnSacuvaj.setVisible(true);
                jBtnObrisi.setEnabled(false);
                jBtnOdustani.setVisible(true);
                jBtnIzmene.setEnabled(false);
                jBtnAzuriraj.setEnabled(false);
                break;
            case FORM_DETAILS:
                jBtnSacuvaj.setEnabled(false);
                jBtnObrisi.setVisible(true);
                jBtnOdustani.setVisible(true);
                jBtnIzmene.setVisible(true);
                jBtnAzuriraj.setEnabled(false);
                
                jTxtTreningID.setEditable(false);
                jTxtDatum.setEditable(false);
                jTxtTrajanje.setEditable(false);
                jTextNapomena.setEditable(false);
                jComboTrener.setEditable(false);
                break;
            case FORM_UPDATE:
                jBtnSacuvaj.setVisible(true);
                jBtnObrisi.setEnabled(false);
                jBtnOdustani.setVisible(true);
                jBtnIzmene.setEnabled(false);
                jBtnAzuriraj.setVisible(true);
                break;
        }
    }
}
